arrowParens: avoid
bracketSpacing: false
# endOfLine: lf
# htmlWhitespaceSensitivity: css
insertPragma: true
# parser: babel
printWidth: 120
proseWrap: never
quoteProps: as-needed
requirePragma: true
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: true
plugins:
  - svelte
svelteSortOrder: options-scripts-markup-styles
svelteStrictMode: false
svelteBracketNewLine: false
svelteAllowShorthand: true
svelteIndentScriptAndStyle: true
